public class WeekMonthMap {
    
    public static void mapfunction(){
        Map<String,Integer> weekmap = new Map<String,Integer>();
        weekmap.put('Jan',1);
        weekmap.put('Feb',2);
        weekmap.put('Mar',3);
        weekmap.put('Apr',4);
        weekmap.put('May',5);
        weekmap.put('Jun',6);
        weekmap.put('Jul',7);
        weekmap.put('Aug',8);
        weekmap.put('Sep',9);
        weekmap.put('Oct',10);
        weekmap.put('Nov',11);
        weekmap.put('Dec',12);
        
        Map<Integer,String> MonthMap2 = new Map<Integer,String>();
        MonthMap2.put(1,'January');
        MonthMap2.put(2,'February');
        MonthMap2.put(3,'March');
        MonthMap2.put(4,'April');
        MonthMap2.put(5,'May');
        MonthMap2.put(6,'June');
        MonthMap2.put(7,'July');
        MonthMap2.put(8,'August');
        MonthMap2.put(9,'September');
        MonthMap2.put(10,'October');
        MonthMap2.put(11,'November');
        MonthMap2.put(12,'December');
    }

}